Fix hosts with wildcards
mercari/certificate-expiry-monitor-controller pull request #3
Opened 2018-10-30 22:26 UTC by ayushpateria

When using wildcards in Ingress's hostnames, the TCP dialup fails and the endpoint is not monitored. This PR replaces '*' with 'www', which should fix this.

2018-11-02 00:29 UTC, vbanthia-zz requested changes

2018-11-02 00:29 UTC, vbanthia commented on source/tls_endpoint.go
> +	hostName := strings.Replace(e.Hostname, "*", "www", -1)
`www` is very common sub-domain. And there are high chances to have different `A` record for this and hosted somewhere else (other than Ingress). This way controller will hit some other host to and get that TLS certificate from that host (Not Ingress Certificate) creating falsey results. I would recommend to use better alternative which are rarely used. May be using `wildcard` work better.

2018-11-06 05:51 UTC, vbanthia-zz approved these changes

2018-11-06 05:54 UTC, babarot approved these changes
Sorry for the late.

Ah, this case... anyway this change looks good to me.

2018-11-06 05:58 UTC, merged